// Generated by gencpp from file motors/arduino_motors.msg
// DO NOT EDIT!


#ifndef MOTORS_MESSAGE_ARDUINO_MOTORS_H
#define MOTORS_MESSAGE_ARDUINO_MOTORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motors
{
template <class ContainerAllocator>
struct arduino_motors_
{
  typedef arduino_motors_<ContainerAllocator> Type;

  arduino_motors_()
    : speed(0)
    , direction()  {
    }
  arduino_motors_(const ContainerAllocator& _alloc)
    : speed(0)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _speed_type;
  _speed_type speed;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::motors::arduino_motors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motors::arduino_motors_<ContainerAllocator> const> ConstPtr;

}; // struct arduino_motors_

typedef ::motors::arduino_motors_<std::allocator<void> > arduino_motors;

typedef boost::shared_ptr< ::motors::arduino_motors > arduino_motorsPtr;
typedef boost::shared_ptr< ::motors::arduino_motors const> arduino_motorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motors::arduino_motors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motors::arduino_motors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motors::arduino_motors_<ContainerAllocator1> & lhs, const ::motors::arduino_motors_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motors::arduino_motors_<ContainerAllocator1> & lhs, const ::motors::arduino_motors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motors

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motors::arduino_motors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motors::arduino_motors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motors::arduino_motors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motors::arduino_motors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motors::arduino_motors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motors::arduino_motors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motors::arduino_motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57336acb67f0c9d5b2d2f2054be77759";
  }

  static const char* value(const ::motors::arduino_motors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57336acb67f0c9d5ULL;
  static const uint64_t static_value2 = 0xb2d2f2054be77759ULL;
};

template<class ContainerAllocator>
struct DataType< ::motors::arduino_motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motors/arduino_motors";
  }

  static const char* value(const ::motors::arduino_motors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motors::arduino_motors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 speed\n"
"string direction\n"
;
  }

  static const char* value(const ::motors::arduino_motors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motors::arduino_motors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arduino_motors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motors::arduino_motors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motors::arduino_motors_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTORS_MESSAGE_ARDUINO_MOTORS_H
